services:
  database:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: guessgame
    ports:
      - "5432:5432"